### ISSUE TITLE
data load

### ISSUE THREAD

**Issue by zhengyuanzang** [toelt-llc/cloud_segmentation_comparative#2]
![微信截图_20240408155350](https://github.com/toelt-llc/cloud_segmentation_comparative/assets/137682005/51160a01-8663-47fc-b327-b526462867b5)

51  with open("cloud_coverage_TOELT_SUPSI/src/download_landsat8_biome.sh", "w") as file:

There is a problem with the address

**Comment by FabioLddo** [comment]
Hello @zangzhengyuan, thank you again for pointing out the problem. I have removed the local paths I found, now it should be correct. Thank you for your patience.

**Comment by safouaneelg** [comment]
Dear community,
This discussion being inactive, I suppose that the problem has been resolved and close the issue.

Thank you for mentioning the problem again.
