### ISSUE TITLE
SPARCS Dataset

### ISSUE THREAD

**Issue by tyou1** [toelt-llc/cloud_segmentation_comparative#3]
Hello,

I noticed that the link for the SPARCS dataset in the `README.md` file is no longer valid and the dataset retrieved from `!wget https://landsat.usgs.gov/cloud-validation/sparcs/l8cloudmasks.zip` isn't exactly the same data types as it looks from the `EDA_SPARCS.ipynb` as follows:

`labels = [f for f in products if '_labels.tif' in f]`
`bands = [f for f in products if '_data.tif' in f]`
`photos = [f for f in products if '_photo.png' in f]`
`qmasks = [f for f in products if '_qmask.tif' in f]`
`c1qba = [f for f in products if '_c1bqa.tif' in f]`

Would it be possible to kindly provide the link for the SPARCS dataset used in this repo?

Thanks!

**Comment by FabioLddo** [comment]
Hi, I have contacted the providers of the dataset we used. It seems that there was a problem with the site and now if I try it it is back online, it should work. Thank you for noticing the problem.
